name: build windows unity plugin

inputs:
  config:
    type: choice
    description: Release Or Debug
    default: 'Release'
    options:
    - Release
    - Debug
  arch:
    type: choice
    description: building arch
    default: 'auto'
    options:
      - auto
      - x64
      - ia32
  websocket:
    description: enable websocket
    default: '0'
  build_proj_dir:
    description: 'build project dir'     
    required: false
    default: 'native'
  GITHUB_TOKEN:
    required:

runs:
  using: "composite"
  steps:
    - name: Build
      shell: powershell
      run: |
        cd unity
        npm i
        cd ${{ inputs.build_proj_dir }}
        cd puerts
        node ../../cli make --platform win --config ${{ inputs.config }} --arch ${{ inputs.arch }} --websocket ${{ inputs.websocket }}
        cd ..
        cd papi-v8
        node ../../cli make --platform win --config ${{ inputs.config }} --arch ${{ inputs.arch }} --websocket ${{ inputs.websocket }}
        cd ..
        cd papi-quickjs
        node ../../cli make --platform win --config ${{ inputs.config }} --arch ${{ inputs.arch }} --websocket ${{ inputs.websocket }}
        cd ..
        cd papi-lua
        node ../../cli make --platform win --config ${{ inputs.config }} --arch ${{ inputs.arch }} --websocket ${{ inputs.websocket }}
        cd ..
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ./unity/Assets/core/upm/Plugins/**/*
        name: Unity_Plugins_${{ inputs.config }}_window
    - name: Clean
      shell: bash
      run: rm -rf ./unity/Assets/core/upm/Plugins/**/*