name: build unity plugins

on: 
  push:
    paths: 
      - unity/native_src/**
      - unity/native_src_ourv8/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - unreal/Puerts/Source/JsEnv/Private/PromiseRejectCallback.hpp
      - .github/workflows/build_unity_plugins.yml

env:
  RUNID: 613573412

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src/
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          export ANDROID_NDK=~/android-ndk-r21b
      - name: Build
        run: |
          ls ~/android-ndk-r21b
          cd unity/native_src
          chmod 777 make_android.sh
          ./make_android.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  android_ourv8:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src_ourv8/
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          export ANDROID_NDK=~/android-ndk-r21b
      - name: Build
        run: |
          ls ~/android-ndk-r21b
          cd unity/native_src_ourv8
          chmod 777 make_android.sh
          ./make_android.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_OUR_V8
  android_qjs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_quickjs.yml
          #run_id: ${{env.RUNID}}
          name: qjs_v8_bin
          path: unity/native_src/
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          export ANDROID_NDK=~/android-ndk-r21b
      - name: Build
        run: |
          ls ~/android-ndk-r21b
          cd unity/native_src
          chmod 777 make_android.sh
          ./make_android_qjs.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_Quickjs
  ios:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src/
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src
          sh ./make_ios.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  ios_ourv8:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src_ourv8/
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src_ourv8
          sh ./make_ios.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_OUR_V8
  ios_qjs:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_quickjs.yml
          #run_id: ${{env.RUNID}}
          name: qjs_v8_bin
          path: unity/native_src/
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src
          sh ./make_ios_qjs.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_Quickjs
  osx:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src/
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src
          sh ./make_osx.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  osx_ourv8:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src_ourv8/
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src_ourv8
          sh ./make_osx.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_OUR_V8
  osx_qjs:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_quickjs.yml
          #run_id: ${{env.RUNID}}
          name: qjs_v8_bin
          path: unity/native_src/
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src
          sh ./make_osx_qjs.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_Quickjs
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src/
      - name: Build
        run: |
          cd unity\native_src
          .\make_win64.bat
          .\make_win32.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  windows_ourv8:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src_ourv8/
      - name: Build
        run: |
          cd unity\native_src_ourv8
          .\make_win64.bat
          .\make_win32.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_OUR_V8
  windows_qjs:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_quickjs.yml
          #run_id: ${{env.RUNID}}
          name: qjs_v8_bin
          path: unity/native_src/
      - name: Build
        run: |
          cd unity\native_src
          .\make_win64_qjs.bat
          .\make_win32_qjs.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_Quickjs
<<<<<<< HEAD
  linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src/
      - name: Build
        run: |
          cd unity/native_src
          chmod 777 make_linux64.sh
          ./make_linux64.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8
  linux_ourv8:
    runs-on: ubuntu-latest
    
    steps:
=======
          
  linux64:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install libc++-dev
        run: |
          sudo apt-get install clang
          sudo apt-get install libc++-dev
          sudo apt-get install libc++abi-dev
>>>>>>> 9195866a522b97bedfae42b1c43784cd7f8acc54
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_v8.yml
          name: v8_bin
          path: unity/native_src/
      - name: Build
        run: |
          cd unity/native_src
          chmod 777 make_linux64.sh
          ./make_linux64.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
<<<<<<< HEAD
          name: Unity_Plugins_OUR_V8
  # linux32:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Download artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         workflow: build_v8.yml
  #         name: v8_bin
  #         path: unity/native_src/
  #     - name: Build
  #       run: |
  #         cd unity/native_src
  #         chmod 777 make_linux32.sh
  #         ./make_linux32.sh
  #     - name: Upload
  #       uses: actions/upload-artifact@v2
  #       with:
  #         path: ./unity/Assets/Plugins/**/*
  #         name: Unity_Plugins_V8
  # linux32_ourv8:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Download artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         workflow: build_v8.yml
  #         name: v8_bin
  #         path: unity/native_src/
  #     - name: Build
  #       run: |
  #         cd unity/native_src
  #         chmod 777 make_linux32.sh
  #         ./make_linux32.sh
  #     - name: Upload
  #       uses: actions/upload-artifact@v2
  #       with:
  #         path: ./unity/Assets/Plugins/**/*
  #         name: Unity_Plugins_OUR_V8
=======
          name: Unity_Plugins_V8
 
>>>>>>> 9195866a522b97bedfae42b1c43784cd7f8acc54
