name: build

on: 
  push:
    paths: 
      - unity/native_src/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - .github/workflows/build.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install NDK
      run: |
        cd ~
        wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
        sudo apt install unzip -y
        unzip -q NDK
        ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
    - name: Build
      run: |
        cd unity/native_src
        chmod 777 make_android.sh
        ./make_android.sh
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./unity/Assets/Plugins/**/*
        name: Puerts-android
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd unity/native_src
          chmod 777 make_ios.sh
          ./make_ios.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Puerts-ios
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd unity/native_src
          chmod 777 make_osx.sh
          ./make_osx.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Puerts-osx
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Insatll MSVC
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[15.0,16.0)'
    - name: Build
      run: |
        cd unity\native_src
        mkdir build64
        cd build64
        cmake -G "Visual Studio 17 2017" ..
        cd ..
        cmake --build build64 --config Release
        mkdir -p ..\Assets\Plugins\x86_64\
        copy .\build64\Release\puerts.dll ..\Assets\Plugins\x86_64\puerts.dll
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./unity/Assets/Plugins/**/*
        name: Puerts-win
  pack:
    runs-on: ubuntu-latest
    needs: [windows, osx,ios,android]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: Puerts-win
          path: artifact/
      - uses: actions/download-artifact@v1
        with:
          name: Puerts-osx
          path: artifact/
      - uses: actions/download-artifact@v1
        with:
          name: Puerts-android
          path: artifact/
      - uses: actions/download-artifact@v1
        with:
          name: Puerts-ios
          path: artifact/
      - uses: actions/upload-artifact@v2
        with:
          name: Puerts-all
          path: artifact/**/*
