name: build quickjs backend

on: 
  push:
    paths: 
      - quickjs-build/**
      - .github/workflows/build_quickjs_backend.yml

jobs:
  build_macos:
    name: macOS
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Use Xcode 12.0 for x86
      run: sudo xcode-select -switch "/Applications/Xcode_12.app"
    - name: Run build script
      run: |
        cd quickjs-build
        ./make_osx.sh
        cp -r include ~/qjs/quickjs/Inc
    - uses: actions/upload-artifact@v2
      with:
        name: qjs_v8_bin
        path: ~/qjs/**/*
        
  build_ios:
    name: iOS
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Use Xcode 12.0 for x86
      run: sudo xcode-select -switch "/Applications/Xcode_12.app"
    - name: Run build script
      run: |
        cd quickjs-build
        ./make_ios.sh
    - uses: actions/upload-artifact@v2
      with:
        name: qjs_v8_bin
        path: ~/qjs/**/*

  build_android:
    name: Android 
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install NDK
      run: |
        cd ~
        wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
        sudo apt install unzip -y
        unzip -q NDK
        export ANDROID_NDK=~/android-ndk-r21b
    - name: Run build script
      run: |
        cd quickjs-build
        ./make_android.sh
    - uses: actions/upload-artifact@v2
      with:
        name: qjs_v8_bin
        path: ~/qjs/**/*

  build_window_dll:
    name: Windows
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: 'cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-dlfcn'
    - shell: msys2 {0}
      run: |
        echo "#! /bin/sh" > /mingw64/bin/make
        echo "\"mingw32-make\" \"\$@\"" >> /mingw64/bin/make
    - shell: msys2 {0}
      run: |
        cd quickjs-build
        ./make_win.sh
    - name: Build
      run: |
        cd quickjs-build\win
        .\make_win64.bat
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Merge Libs
      run: |
        cd quickjs-build\win
        LIB.EXE /OUT:quickjs.dll.lib ..\build\libquickjs.dll.a build\Release\v8qjs.lib
    - name: Prepare
      shell: msys2 {0}
      run: |
        mkdir -p qjs/quickjs/Lib/Win64/
        cp quickjs-build/win/quickjs.dll.lib qjs/quickjs/Lib/Win64/
        cp quickjs-build/build/msys-quickjs.dll qjs/quickjs/Lib/Win64/
        cp /mingw64/bin/libgcc_s_seh-1.dll qjs/quickjs/Lib/Win64/
        cp /mingw64/bin/libwinpthread-1.dll qjs/quickjs/Lib/Win64/
    - uses: actions/upload-artifact@v2
      with:
        name: qjs_v8_bin
        path: qjs/**/*
        
  build_window_dll_md:
    name: Windows MD
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
    - name: Insatll MSVC
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: 'cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-dlfcn'
    - shell: msys2 {0}
      run: |
        echo "#! /bin/sh" > /mingw64/bin/make
        echo "\"mingw32-make\" \"\$@\"" >> /mingw64/bin/make
    - shell: msys2 {0}
      run: |
        cd quickjs-build
        ./make_win.sh
    - name: Build
      run: |
        cd quickjs-build\win
        .\make_win64md.bat
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Merge Libs
      run: |
        cd quickjs-build\win
        LIB.EXE /OUT:quickjs.dll.lib ..\build\libquickjs.dll.a build\Release\v8qjs.lib
    - name: Prepare
      shell: msys2 {0}
      run: |
        mkdir -p qjs/quickjs/Lib/Win64MD/
        cp quickjs-build/win/quickjs.dll.lib qjs/quickjs/Lib/Win64MD/
        cp quickjs-build/build/msys-quickjs.dll qjs/quickjs/Lib/Win64MD/
        cp /mingw64/bin/libgcc_s_seh-1.dll qjs/quickjs/Lib/Win64MD/
        cp /mingw64/bin/libwinpthread-1.dll qjs/quickjs/Lib/Win64MD/
    - uses: actions/upload-artifact@v2
      with:
        name: qjs_v8_bin
        path: qjs/**/*

  build_window_dll32:
    name: Windows32
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: 'cmake mingw-w64-i686-gcc mingw-w64-i686-make mingw-w64-i686-dlfcn'
    - shell: msys2 {0}
      run: |
        echo "#! /bin/sh" > /mingw32/bin/make
        echo "\"mingw32-make\" \"\$@\"" >> /mingw32/bin/make
    - shell: msys2 {0}
      run: |
        cd quickjs-build
        ./make_win.sh
    - name: Build
      run: |
        cd quickjs-build\win
        .\make_win32.bat
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Merge Libs
      run: |
        cd quickjs-build\win
        LIB.EXE /OUT:quickjs.dll.lib ..\build\libquickjs.dll.a build\Release\v8qjs.lib
    - name: Prepare
      shell: msys2 {0}
      run: |
        mkdir -p qjs/quickjs/Lib/Win32/
        cp quickjs-build/win/quickjs.dll.lib qjs/quickjs/Lib/Win32/
        cp quickjs-build/build/msys-quickjs.dll qjs/quickjs/Lib/Win32/
        cp /mingw32/bin/libgcc_s_dw2-1.dll qjs/quickjs/Lib/Win32/
        cp /mingw32/bin/libwinpthread-1.dll qjs/quickjs/Lib/Win32/
    - uses: actions/upload-artifact@v2
      with:
        name: qjs_v8_bin
        path: qjs/**/*

